"""Exporta el arte del juego a Godot.

Uso:  uv run build_game_assets.py
Salida:
  ../assets/generated/            SVG sin filtros ni texto (el brillo lo pone el motor)
  ../assets/generated/manifest.json   lista de assets con su tamaño y su origen
  ../core/palette.gd              la paleta como constantes de GDScript (clase Palette)

Los SVG se importan en Godot con `svg/scale = 2` y se dibujan a escala 0,5, para
que queden nítidos aunque la ventana sea mayor que 1280×720.
"""

import json
from collections.abc import Callable
from pathlib import Path

from atomic_art import characters as C
from atomic_art import palette as P
from atomic_art.svg import doc, g

ROOT = Path(__file__).resolve().parent
PROJECT = ROOT.parent
OUT = PROJECT / "assets" / "generated"
PALETTE_GD = PROJECT / "core" / "palette.gd"

# Lienzos (ancho, alto) de las piezas de Wilas. Todas comparten el centro del núcleo.
CORE_CANVAS = (52, 52)
ORBITAL_CANVAS = (72, 72)
ELECTRON_CANVAS = (8, 8)

# (ruta relativa a OUT, lienzo, función que devuelve el SVG centrado en (0, 0), origen)
Asset = tuple[str, tuple[int, int], Callable[[], str], str]

ASSETS: list[Asset] = [
    ("player/player_core.svg", CORE_CANVAS, C.wilas_core, "characters.wilas_core"),
    ("player/player_orbital.svg", ORBITAL_CANVAS, C.wilas_orbital, "characters.wilas_orbital"),
    ("player/player_orbital_front.svg", ORBITAL_CANVAS, C.wilas_orbital_front, "characters.wilas_orbital_front"),
    ("player/player_electron.svg", ELECTRON_CANVAS, C.wilas_electron, "characters.wilas_electron"),
] + [
    (f"player/player_eyes_{expr}.svg", CORE_CANVAS, (lambda e=expr: C.wilas_eyes(e)), f"characters.wilas_eyes('{expr}')")
    for expr in C.EXPRESSIONS
]


def export_svg(body: str, size: tuple[int, int]) -> str:
    """SVG de juego: centrado en el lienzo, sin filtros de brillo ni texto."""
    w, h = size
    svg = doc(w, h, g(body, x=w / 2, y=h / 2), glow=False)
    assert "filter" not in svg and "<text" not in svg, "Los SVG del juego no llevan filtros ni texto"
    return svg


def color_literal(hex_color: str) -> str:
    r, g_, b = P.hex_to_rgb(hex_color)
    return f"Color({r / 255:.4f}, {g_ / 255:.4f}, {b / 255:.4f})"


def palette_gd() -> str:
    """La paleta como clase de GDScript, con el formato de gdformat."""
    tokens = {
        "VOID": P.VOID,
        "VOID_2": P.VOID_2,
        "VOID_3": P.VOID_3,
        "GRID": P.GRID,
        "INK": P.INK,
        "INK_DIM": P.INK_DIM,
        "PLAYER": P.PLAYER,
        "PLAYER_DEEP": P.PLAYER_DEEP,
        "NEGATIVE": P.NEGATIVE,
        "POSITIVE": P.POSITIVE,
        "NEUTRAL": P.NEUTRAL,
        "DECOHERENCE": P.DECOHERENCE,
        "DANGER": P.DANGER,
        "PHOTON": P.PHOTON,
        "POSITRON": P.POSITRON,
        "HIGGS": P.HIGGS,
    }
    tokens |= {f"FAMILY_{k.upper()}": v for k, v in P.FAMILY.items()}
    tokens |= {f"RARITY_{k.upper()}": v for k, v in P.RARITY.items()}
    for layer, info in P.LAYER.items():
        tokens[f"LAYER_{layer}_TINT"] = info["tint"]
        tokens[f"LAYER_{layer}_ACCENT"] = info["accent"]
    lines = [
        "class_name Palette",
        "extends RefCounted",
        "## Colors of the art direction (docs/13-art-style.md#paleta).",
        "## Generated by art/build_game_assets.py from art/atomic_art/palette.py: do not edit.",
        "",
    ]
    lines += [f"const {name}: Color = {color_literal(value)}  # {value.upper()}" for name, value in tokens.items()]
    return "\n".join(lines) + "\n"


def main() -> None:
    if OUT.exists():
        # Se borran los SVG y el manifiesto, pero no los .import de Godot, que
        # guardan la escala de importación y los uid de cada asset
        for svg in OUT.rglob("*.svg"):
            svg.unlink()
    OUT.mkdir(parents=True, exist_ok=True)
    manifest: dict[str, dict] = {}
    for rel, size, fn, source in ASSETS:
        out = OUT / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(export_svg(fn(), size), encoding="utf-8")
        manifest[rel] = {"size": list(size), "source": source}
        print("  ", rel)
    # Assets que ya no existen: su .import queda huérfano
    for imported in OUT.rglob("*.svg.import"):
        if imported.with_suffix("").relative_to(OUT).as_posix() not in manifest:
            imported.unlink()
            print("   (borrado)", imported.relative_to(OUT))
    (OUT / "manifest.json").write_text(
        json.dumps({"generator": "art/build_game_assets.py", "assets": manifest}, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    PALETTE_GD.write_text(palette_gd(), encoding="utf-8")
    print(f"Listo → {OUT.relative_to(PROJECT)} y {PALETTE_GD.relative_to(PROJECT)}")


if __name__ == "__main__":
    main()
