class_name Palette
extends RefCounted
## Colors of the art direction (docs/13-art-style.md#paleta).
## Generated by art/build_game_assets.py from art/atomic_art/palette.py: do not edit.

const VOID: Color = Color(0.0196, 0.0275, 0.0588)  # #05070F
const VOID_2: Color = Color(0.0431, 0.0627, 0.1333)  # #0B1022
const VOID_3: Color = Color(0.0784, 0.1059, 0.2118)  # #141B36
const GRID: Color = Color(0.1098, 0.1451, 0.2784)  # #1C2547
const INK: Color = Color(0.9176, 0.9490, 1.0000)  # #EAF2FF
const INK_DIM: Color = Color(0.5490, 0.5922, 0.7216)  # #8C97B8
const PLAYER: Color = Color(0.4196, 1.0000, 0.7216)  # #6BFFB8
const PLAYER_DEEP: Color = Color(0.1216, 0.6824, 0.4784)  # #1FAE7A
const NEGATIVE: Color = Color(0.2392, 0.9098, 1.0000)  # #3DE8FF
const POSITIVE: Color = Color(1.0000, 0.2392, 0.5451)  # #FF3D8B
const NEUTRAL: Color = Color(0.8627, 0.8902, 0.9608)  # #DCE3F5
const DECOHERENCE: Color = Color(0.7882, 0.8235, 1.0000)  # #C9D2FF
const DANGER: Color = Color(1.0000, 0.2392, 0.5451)  # #FF3D8B
const PHOTON: Color = Color(1.0000, 0.8941, 0.3608)  # #FFE45C
const POSITRON: Color = Color(1.0000, 0.2392, 0.5451)  # #FF3D8B
const HIGGS: Color = Color(1.0000, 0.8235, 0.3529)  # #FFD25A
const FAMILY_ELECTROMAGNETIC: Color = Color(1.0000, 0.8941, 0.3608)  # #FFE45C
const FAMILY_STRONG: Color = Color(1.0000, 0.4157, 0.2392)  # #FF6A3D
const FAMILY_WEAK: Color = Color(0.7765, 1.0000, 0.2392)  # #C6FF3D
const FAMILY_GRAVITY: Color = Color(0.5608, 0.4824, 1.0000)  # #8F7BFF
const FAMILY_QUANTUM: Color = Color(1.0000, 0.4824, 0.9451)  # #FF7BF1
const RARITY_COMMON: Color = Color(0.9176, 0.9490, 1.0000)  # #EAF2FF
const RARITY_RARE: Color = Color(0.3020, 0.6392, 1.0000)  # #4DA3FF
const RARITY_EPIC: Color = Color(0.6902, 0.4196, 1.0000)  # #B06BFF
const RARITY_LEGENDARY: Color = Color(1.0000, 0.8235, 0.3529)  # #FFD25A
const LAYER_K_TINT: Color = Color(0.1843, 0.4196, 1.0000)  # #2F6BFF
const LAYER_K_ACCENT: Color = Color(0.4980, 0.6902, 1.0000)  # #7FB0FF
const LAYER_L_TINT: Color = Color(0.0706, 0.7882, 0.7059)  # #12C9B4
const LAYER_L_ACCENT: Color = Color(0.4863, 0.9608, 0.8941)  # #7CF5E4
const LAYER_M_TINT: Color = Color(0.5490, 0.3020, 1.0000)  # #8C4DFF
const LAYER_M_ACCENT: Color = Color(0.7804, 0.6510, 1.0000)  # #C7A6FF
const LAYER_N_TINT: Color = Color(1.0000, 0.2392, 0.3843)  # #FF3D62
const LAYER_N_ACCENT: Color = Color(1.0000, 0.6157, 0.6902)  # #FF9DB0
