class_name Level
extends Node2D
## A run's level: the layer generated by the seed (LayerGenerator) as a column
## of chunks, a camera that follows the player and the Decoherence (RisingThreat)
## rising from below. The chunks near the player are instantiated lazily and the
## ones left under the Decoherence are freed. The column ends at the first fork
## without a choice: crossing one of its exits records the branch in the run and
## adds that branch to the column. Reaching the top of the layer ends the run as
## completed (the boss and the next layers arrive in later phases); dying ends it.

## Altitude units (pm) per chunk height of one screen (the prototype counted 11).
const ALTITUDE_UNITS_PER_CHUNK: float = 11.0
const PX_PER_UNIT: float = ChunkData.DEFAULT_HEIGHT_TILES * Chunk.TILE / ALTITUDE_UNITS_PER_CHUNK
const LAYER_K: LayerData = preload("res://data/layers/layer_k.tres")

## Layers of the run, in order.
@export var layers: Array[LayerData] = [LAYER_K]
## Px below the bottom of the layer where the Decoherence starts.
@export var threat_start_depth: float = 500.0
## Chunks kept instantiated above and below the player's.
@export var chunks_ahead: int = 2
@export var chunks_behind: int = 1
## Seconds a chunk that appears on screen takes to fade in.
@export var chunk_fade_time: float = 0.25

var run: RunState = null
var layer: LayerData = null
var plan: LayerPlan = null
var _library: ChunkLibrary = null
## Placements of the column, bottom up, and the world y of each one's top edge.
var _column: Array[ChunkPlacement] = []
var _tops: PackedFloat32Array = []
## Chunks in the world by index in the column.
var _chunks: Dictionary[int, Chunk] = {}
## Indices below this were freed for good (nobody can go back there).
var _first_alive: int = 0
var _start_y: float = 0.0
var _ending: bool = false

@onready var _chunks_root: Node2D = %Chunks
@onready var _camera: PlayerCamera = %Camera
@onready var _player: Player = %Player
@onready var _threat: RisingThreat = %RisingThreat
@onready var _hud: Hud = %Hud
@onready var _projectiles: Node2D = %Projectiles
@onready var _hit_stop: HitStop = %HitStop


func _ready() -> void:
	# Running the level scene on its own (F6) starts a random run
	run = RunManager.run if RunManager.has_run() else RunManager.start_run()
	layer = layers[mini(run.layer_index, layers.size() - 1)]
	_library = ChunkLibrary.from_layers(layers)
	plan = LayerGenerator.new(_library).generate(layer, run.world_rng)
	_rebuild_column()
	_update_chunks()

	_player.bind_run(run)
	_player.set_projectile_parent(_projectiles)
	_player.hurt.connect(_on_player_hurt)
	Events.enemy_damaged.connect(_on_enemy_damaged)
	Events.enemy_killed.connect(_on_enemy_killed)
	_hud.bind_run(run)
	run.died.connect(_end_run.bind(false))
	var spawn: Marker2D = _chunks[0].get_marker(Chunk.SPAWN_MARKER)
	if spawn != null:
		_player.global_position = spawn.global_position - Vector2(0.0, _player.get_feet_offset())
	_start_y = _player.global_position.y

	_camera.area_left = 0.0
	_camera.area_right = Chunk.WIDTH
	_camera.area_bottom = get_bottom()
	_camera.target = _player
	_camera.snap_to_target()

	_threat.base_speed = layer.threat_speed
	_threat.position = Vector2(0.0, get_bottom() + threat_start_depth)
	_threat.scan_left = Chunk.INNER_LEFT
	_threat.scan_right = Chunk.INNER_RIGHT
	_threat.setup(_player)
	_update_chunks()


func _physics_process(_delta: float) -> void:
	_threat.paused = is_safe_at(_player.global_position.y)
	_update_chunks()
	var height: float = (_start_y - _player.global_position.y) / PX_PER_UNIT
	if height > run.altitude:
		run.set_altitude(height)
	var feet_y: float = _player.global_position.y + _player.get_feet_offset()
	run.set_threat_distance(maxf(0.0, _threat.distance_to(feet_y)) / PX_PER_UNIT)
	if plan.is_complete(_choices()) and feet_y < _tops[_tops.size() - 1]:
		_end_run(true)


## World y of the bottom edge of the layer.
func get_bottom() -> float:
	return _tops[0] + _library.get_info(_column[0].chunk_id).data.height_tiles * Chunk.TILE


func get_column() -> Array[ChunkPlacement]:
	return _column


## World y of the top edge of the chunk at `index` in the column.
func get_chunk_top(index: int) -> float:
	return _tops[index]


## Chunk instantiated at `index` in the column, or null.
func get_chunk(index: int) -> Chunk:
	return _chunks.get(index)


## Index in the column of the chunk that contains the world height `y`
## (clamped to the column: below it is 0, above it the last one).
func chunk_index_at(y: float) -> int:
	# Tops go up (decrease) with the index: the first one above `y` holds it
	for index: int in _tops.size():
		if y >= _tops[index]:
			return index
	return _tops.size() - 1


## Whether the chunk at the world height `y` is safe (the Decoherence stops).
func is_safe_at(y: float) -> bool:
	var chunk: Chunk = _chunks.get(chunk_index_at(y))
	return chunk != null and chunk.is_safe()


func _choices() -> PackedStringArray:
	return run.get_choices(layer.code)


## Recomputes the column for the choices made so far, keeping the chunks
## already in the world (the column only grows upwards).
func _rebuild_column() -> void:
	_column = plan.column(_choices())
	_tops.resize(_column.size())
	# The first chunk's top is at y = 0; each one sits on the previous one
	var top: float = 0.0
	for index: int in range(1, _column.size()):
		top -= _library.get_info(_column[index].chunk_id).data.height_tiles * Chunk.TILE
		_tops[index] = top
	if not _column.is_empty():
		_tops[0] = 0.0


## Instantiates the chunks from `chunks_behind` below the player's to
## `chunks_ahead` above it, and frees the ones left under both the Decoherence
## and the view.
func _update_chunks() -> void:
	var current: int = chunk_index_at(_player.global_position.y)
	var first: int = maxi(_first_alive, current - chunks_behind)
	for index: int in range(first, mini(_column.size(), current + chunks_ahead + 1)):
		if not _chunks.has(index):
			_add_chunk(index)
	var view_size: Vector2 = _camera.get_view_size()
	var bottom_limit: float = maxf(
		_threat.global_position.y, _camera.global_position.y + view_size.y / 2.0
	)
	for index: int in _chunks.keys():
		if _tops[index] > bottom_limit:
			_chunks[index].queue_free()
			_chunks.erase(index)
			_first_alive = maxi(_first_alive, index + 1)


func _add_chunk(index: int) -> void:
	var placement: ChunkPlacement = _column[index]
	var chunk: Chunk = _library.get_info(placement.chunk_id).scene.instantiate()
	chunk.position = Vector2(0.0, _tops[index])
	build_chunk(chunk, placement, layer, run.world_rng, run.layer_index)
	if placement.type == ChunkData.Type.FORK:
		chunk.branch_chosen.connect(_on_branch_chosen.bind(placement))
	_chunks_root.add_child(chunk)
	_chunks[index] = chunk
	if is_node_ready() and _is_on_screen(chunk):
		chunk.modulate.a = 0.0
		create_tween().tween_property(chunk, ^"modulate:a", 1.0, chunk_fade_time)


## Prepares a chunk for its placement before it enters the tree: mirror,
## optional parts, slots, and its fork exits or its reward. Also used by the
## chunk test room.
static func build_chunk(
	chunk: Chunk,
	placement: ChunkPlacement,
	layer_data: LayerData,
	rng: WorldRng,
	layer_index: int = 0
) -> void:
	var key: Array = placement.key()
	if placement.mirrored:
		chunk.apply_mirror()
	chunk.set_optional_parts(
		LayerGenerator.pick_optional_parts(
			rng, key, ChunkInfo.read_optional_parts(chunk), layer_data.optional_part_chance
		)
	)
	chunk.fill_slots(
		SlotFiller.plan(rng, layer_data, key, ChunkInfo.read_slots(chunk)), key, rng, layer_index
	)
	match placement.type:
		ChunkData.Type.FORK:
			chunk.setup_fork(LayerGenerator.pick_fork_rewards(rng, layer_data, placement.fork))
		ChunkData.Type.REWARD:
			chunk.spawn_reward(placement.reward)


func _is_on_screen(chunk: Chunk) -> bool:
	var view_size: Vector2 = _camera.get_view_size()
	var view_top: float = _camera.global_position.y - view_size.y / 2.0
	return (
		chunk.position.y < view_top + view_size.y
		and chunk.position.y + chunk.get_height() > view_top
	)


func _on_branch_chosen(side: int, placement: ChunkPlacement) -> void:
	run.choose_branch(
		"%s/%s" % [layer.code, LayerPlan.branch_id(placement.fork, LayerPlan.SIDES[side])]
	)
	_rebuild_column()
	_update_chunks()


## Ends the run once and shows the end screen (`completed`: the top of the
## layer was reached). The level stops while it fades.
func _end_run(completed: bool) -> void:
	if _ending:
		return
	_ending = true
	process_mode = Node.PROCESS_MODE_DISABLED
	var ended: RunState = RunManager.end_run()
	SceneRouter.go_to(SceneRouter.GAME_OVER, {"run": ended, "completed": completed})


func _on_player_hurt() -> void:
	_hit_stop.stop(_hit_stop.player_hurt_time)


func _on_enemy_damaged(_enemy_id: StringName) -> void:
	_hit_stop.stop(_hit_stop.enemy_hit_time)


func _on_enemy_killed(_enemy_id: StringName, _position: Vector2) -> void:
	_hit_stop.stop(_hit_stop.enemy_kill_time)


func _on_pause_menu_menu_button_pressed() -> void:
	RunManager.end_run()
	SceneRouter.go_to(SceneRouter.MAIN_MENU)


func _on_pause_menu_exit_button_pressed() -> void:
	get_tree().quit()
